version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0
  aws-ecr: orbies/aws-ecr@1.0.5

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  pre-integration-checkout-workspace-job:
    executor:
      name: orb-tools/alpine
      resource-class: small
    steps:
      - checkout

      - persist_to_workspace:
          root: .
          paths: [sample/Dockerfile]

workflows:
  lint-pack_validate_deploy-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: orbies/aws-ecr
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-tests-workflow:
          context: orb-publishing
          requires: [orb-tools/publish-dev]

  integration-tests_deploy-prod:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - pre-integration-checkout-workspace-job:
          name: pre-integration

      - aws-ecr/push-helm-chart:
          name: integration-tests-helm-chart-named-profile
          context: orb-publishing
          attach-workspace: true
          workspace-root: workspace
          profile-name: testing
          repo: aws-ecr-orb-helm-${CIRCLE_SHA1:0:7}-named-profile
          create-repo: true
          tag: integration
          path: sample/mychart
          post-steps:
            - run: aws ecr delete-repository --repository-name aws-ecr-orb-helm-${CIRCLE_SHA1:0:7}-named-profile --force
          requires: [pre-integration]

      - aws-ecr/push-helm-chart:
          name: integration-tests-helm-chart-default-profile
          context: orb-publishing
          attach-workspace: true
          workspace-root: workspace
          repo: aws-ecr-orb-helm-${CIRCLE_SHA1:0:7}-default-profile
          create-repo: true
          tag: integration
          path: sample/mychart
          post-steps:
            - run: aws ecr delete-repository --repository-name aws-ecr-orb-helm-${CIRCLE_SHA1:0:7}-default-profile --force
          requires: [pre-integration]

      - aws-ecr/build-and-push-image:
          name: integration-tests-default-profile
          context: orb-publishing
          attach-workspace: true
          workspace-root: workspace
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile
          create-repo: true
          tag: integration,myECRRepoTag
          dockerfile: sample/Dockerfile
          path: workspace
          extra-build-args: --compress
          post-steps:
            - run: aws ecr delete-repository --repository-name aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile --force
          requires: [pre-integration]

      - aws-ecr/build-and-push-image:
          name: integration-tests-named-profile
          context: orb-publishing
          attach-workspace: true
          workspace-root: workspace
          profile-name: testing
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-named-profile
          create-repo: true
          tag: integration,myECRRepoTag
          dockerfile: sample/Dockerfile
          path: workspace
          extra-build-args: --compress
          post-steps:
            - run: aws ecr delete-repository --repository-name aws-ecr-orb-${CIRCLE_SHA1:0:7}-named-profile --force
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          requires: [pre-integration]

      - aws-ecr/build-and-push-image:
          name: integration-tests-skip-when-tags-exist-populate-image
          context: orb-publishing
          attach-workspace: true
          workspace-root: workspace
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-skip-when-tags-exist
          create-repo: true
          tag: integration,myECRRepoTag
          dockerfile: sample/Dockerfile
          path: workspace
          extra-build-args: --compress
          skip-when-tags-exist: true
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          requires: [pre-integration]

      - aws-ecr/build-and-push-image:
          name: integration-tests-skip-when-tags-exist
          context: orb-publishing
          attach-workspace: true
          workspace-root: workspace
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-skip-when-tags-exist
          tag: integration,myECRRepoTag
          dockerfile: sample/Dockerfile
          path: workspace
          extra-build-args: --compress
          skip-when-tags-exist: true
          post-steps:
            - run: aws ecr delete-repository --repository-name aws-ecr-orb-${CIRCLE_SHA1:0:7}-skip-when-tags-exist --force
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          requires: [integration-tests-skip-when-tags-exist-populate-image]

      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: orbies/aws-ecr
          context: orb-publishing
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: 54:b8:9b:79:74:29:3e:dd:95:52:4d:4b:e6:8b:38:f2
          filters:
            branches:
              only: master
          requires:
            - integration-tests-default-profile
            - integration-tests-named-profile
            - integration-tests-skip-when-tags-exist
            - integration-tests-helm-chart-default-profile
            - integration-tests-helm-chart-named-profile
